services:
  # 1. Servicio de Base de Datos
  focalizze-db:
    image: mysql:8.0
    container_name: focalizze_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: focalizze_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # --- AGREGADO: CHEQUEO DE SALUD ---
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. Servicio de tu Backend (Spring Boot)
  focalizze-app:
    image: focalizze-backend:latest
    container_name: focalizze_app_container
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://focalizze-db:3306/focalizze_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET_KEY: una_clave_secreta_muy_larga_para_produccion_que_sea_segura_123456
      FILE_UPLOAD_DIR: /app/uploads
      APP_DEFAULT_AVATAR_URL: http://localhost:8080/images/default-avatar.png
    volumes:
      - ./uploads:/app/uploads
    # --- MODIFICADO: ESPERAR A QUE ESTÃ‰ SANO ---
    depends_on:
      focalizze-db:
        condition: service_healthy

volumes:
  mysql_data: